<a href="https://colab.research.google.com/github/Gursewak-S/Advance-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [ ]:
# Numpy -> Numpy is an open-source Library that is used for scintific calculations.

In [ ]:
# Why Numpy is better than List ?
# 1. Numpy (Homogeneous data type) , List(Hetrogeneous data type)
# 2. Numpy(time Less consumption) , List(more time consumption)
# 3. Numpy(Less memory consume) , List(more memory consume)

In [2]:
import numpy as np

In [ ]:
a = [1,45,89,90]
type (a)

list

In [ ]:
b = np.array(a)
b

array([ 1, 45, 89, 90])

In [ ]:
c = [[1,2,3], [4,5,6], [7,8,9]]
d = np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Total Rows and columns:", d. shape)   ##shape = n(rows) , n(coLumns)
print("Total Elements:" , d.size)         ##size = n(rows)*n(columns)
print("Total Dimension:" , d.ndim)

Total Rows and columns: (3, 3)
Total Elements: 9
Total Dimension: 2


In [ ]:
b.ndim

1

# User Defined array

In [ ]:
a = []
size = int(input("Enter Size: "))
for i in range(size):
  val = int(input("Enter values: "))
  a.append(val)

b = np.array(a)
b

Enter Size: 3
Enter values: 1
Enter values: 48
Enter values: 541


array([  1,  48, 541])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

# Pre-defined Function of Numpy

In [ ]:
# 1. zeros() => It will create an array in which all the value will be 0.

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#  2. ones() => It will create an array in which all the value will be 1.

In [ ]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 3. eye() => It will create an array in which diagonal positional element will be 1 and rest all will be zero

In [ ]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.eye(5,5)   # n(r) = n(c)  ---> Symmatric Matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.eye(3,4)    # n(r) != n(c)  ---> Asymmatric Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#  4. diag() => It will create an array the will set diagonal positional custom values.

In [ ]:
a = np.diag([10,20,456,8000])
a

array([[  10,    0,    0,    0],
       [   0,   20,    0,    0],
       [   0,    0,  456,    0],
       [   0,    0,    0, 8000]])

# Random Module

In [ ]:
# (a). Randint() => It will generate random values based on fix criteria.
# np.random.randint(min_range, max_range, total_number)

In [ ]:
a=np.random.randint(1,10,3)
print(a)

[5 7 9]


In [ ]:
# (b). Rand() --> It will generate random numbers from 0 to 1.

In [ ]:
a=np.random.rand(5)
a

array([0.47237913, 0.38615209, 0.744137  , 0.33524208, 0.59543829])

In [ ]:
# (c). randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well .

# syntax == random.randn(number of values)

In [20]:
a = np.random.randn(5)
a

array([ 0.75093261, -2.11632502, -0.87362053,  0.22286415, -1.54902911])

In [ ]:
# (d). seed() => it will fix our random generated data

In [27]:
np.random.seed(30)   # pass any random no like 30 to lock the random generated no
a = np.random.randint(1,10,3)
print(a)

[6 6 5]


# View  Vs Copy

In [ ]:
a=np.array([10,20,30,40,50,60,70,80])  # View method
b=a[3:6]
b[:]=0
print(b)
print(a)

[0 0 0]
[10 20 30  0  0  0 70 80]


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])  # Copy method
b=a[3:6].copy()
b[:]=0
print(b)
print(a)

[0 0 0]
[10 20 30 40 50 60 70 80]


# Reshaping the Array


In [ ]:
# n(rows) * n(columns) = n(total_elements)

In [ ]:
a=np.random.randint(1,50,12)
print(a)

[13 24  3 18 47  4 42  8  2 46 36 19]


In [ ]:
a.reshape(2,6)

array([[13, 24,  3, 18, 47,  4],
       [42,  8,  2, 46, 36, 19]])

In [ ]:
a.reshape(6,2)

array([[13, 24],
       [ 3, 18],
       [47,  4],
       [42,  8],
       [ 2, 46],
       [36, 19]])

In [ ]:
print(a.reshape(3,4))

[[13 24  3 18]
 [47  4 42  8]
 [ 2 46 36 19]]


In [ ]:
print(a.reshape(4,3))

[[13 24  3]
 [18 47  4]
 [42  8  2]
 [46 36 19]]


# Conditional Selection in Numpy

In [ ]:
a=np.arange(1,15)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
print(a>10)

[False False False False False False False False False False  True  True
  True  True]


In [ ]:
b=a>10
print(a[b])

[11 12 13 14]


In [ ]:
print(a[a%2==0])

[ 2  4  6  8 10 12 14]


In [ ]:
a=np.array([1,2,3,4])
print(a**2)

[ 1  4  9 16]


In [ ]:
print(a**3)

[ 1  8 27 64]


In [ ]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
print(a)

[[1 2]
 [3 4]]


In [ ]:
b=np.array([5,6,7,8]).reshape(2,2)
print(b)

[[5 6]
 [7 8]]


In [ ]:
print(a+b)

[[ 6  8]
 [10 12]]


In [ ]:
print(a-b)

[[-4 -4]
 [-4 -4]]


In [ ]:
print(a.dot(b)) # for matrix multiplication

[[19 22]
 [43 50]]


In [ ]:
# Unique() --> It will return 3 arrays.

# 1. Arr --> Unique value store
# 2. return_index = True --> In which indexing we have unique values
# 3. return_counts = True --> Frequency of each element

In [ ]:
a=np.array([1,2,2,3,3,3,3,3,1,1,2,7,8,4])
print(a)

[1 2 2 3 3 3 3 3 1 1 2 7 8 4]


In [ ]:
np.unique(a,return_index = True, return_counts = True)

(array([1, 2, 3, 4, 7, 8]),
 array([ 0,  1,  3, 13, 11, 12]),
 array([3, 3, 5, 1, 1, 1]))

In [ ]:
# LinSpace() => It will create an array in which gap of values are equal.

In [ ]:
a = np.linspace(1,2,5)  # linspace(starting_value , Ending_value, Total_no)
print(a)

[1.   1.25 1.5  1.75 2.  ]


# Stacking in Numpy

In [ ]:
# hstack => It will combined arrays in horizontally.

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# vstack() => It will combined arrays in vertically.

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# some more important numpy functions

In [21]:
a = np.array([10,20,30,40,50])
np.min(a)

10

In [22]:
np.max(a)   #it will return maximum value of the array

50

In [23]:
np.argmin(a)  #it will return indexing of minimum value

0

In [24]:
np.argmax(a)   # it will return indexing of maximum value

4

In [25]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [26]:
np.cumsum(a) #### a,b,c,d = a , a+b , a+b+c , a+b+c+d

array([ 10,  30,  60, 100, 150])

# Learning Assign

In [3]:
# Q.1 = Write statement to import numpy ?

import numpy as np

In [4]:
# Q.2 = Create an array using numpy ?

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
# Q.3 = Create an array of 10 random integers ?

a = np.random.randint(1,100,5)
a

array([35, 41, 35,  6, 18])

In [10]:
# Q.4 = Create an array of elements from  10-20?

a = []
for i in range(10,21):
  a.append(i)

a = np.array(a)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
# Q.5 = Create an array which contains value 5 , 10 times ?
a = [5]
a = a*10
a = np.array(a)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
# Q.6 = Create a one dimensional array and convert that into 3*3 matrix ?

a = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])
a.reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
# Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?

a = np.linspace(0,1,9)
a.reshape(3,3)

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [19]:
# Q.8 = Concatenate 2D array horizontally and vertically ?

a = np.array([10, 11, 12, 13]).reshape(2,2)
b = np.array([14, 15, 16, 17]).reshape(2,2)

print(np.hstack((a,b)))
print(np.vstack((a,b)))


[[10 11 14 15]
 [12 13 16 17]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]]
