<a href="https://colab.research.google.com/github/Gursewak-S/Advance-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [ ]:
# Numpy -> Numpy is an open-source Library that is used for scintific calculations.

In [ ]:
# Why Numpy is better than List ?
# 1. Numpy (Homogeneous data type) , List(Hetrogeneous data type)
# 2. Numpy(time Less consumption) , List(more time consumption)
# 3. Numpy(Less memory consume) , List(more memory consume)

In [2]:
import numpy as np

In [3]:
a = [1,45,89,90]
type (a)

list

In [4]:
b = np.array(a)
b

array([ 1, 45, 89, 90])

In [5]:
c = [[1,2,3], [4,5,6], [7,8,9]]
d = np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print("Total Rows and columns:", d. shape)   ##shape = n(rows) , n(coLumns)
print("Total Elements:" , d.size)         ##size = n(rows)*n(columns)
print("Total Dimension:" , d.ndim)

Total Rows and columns: (3, 3)
Total Elements: 9
Total Dimension: 2


In [7]:
b.ndim

1

# User Defined array

In [10]:
a = []
size = int(input("Enter Size: "))
for i in range(size):
  val = int(input("Enter values: "))
  a.append(val)

b = np.array(a)
b

Enter Size: 3
Enter values: 1
Enter values: 48
Enter values: 541


array([  1,  48, 541])

In [9]:
type(b)

numpy.ndarray

In [11]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

# Pre-defined Function of Numpy

In [13]:
# 1. zeros() => It will create an array in which all the value will be 0.

In [14]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [16]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#  2. ones() => It will create an array in which all the value will be 1.

In [18]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# 3. eye() => It will create an array in which diagonal positional element will be 1 and rest all will be zero

In [21]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
a = np.eye(5,5)   # n(r) = n(c)  ---> Symmatric Matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
a = np.eye(3,4)    # n(r) != n(c)  ---> Asymmatric Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
#  4. diag() => It will create an array the will set diagonal positional custom values.

In [25]:
a = np.diag([10,20,456,8000])
a

array([[  10,    0,    0,    0],
       [   0,   20,    0,    0],
       [   0,    0,  456,    0],
       [   0,    0,    0, 8000]])